import time

"""
Intelligent Code Architecture Analyzer & Enhancement Engine

Why: Transform the Why/Where/How documentation system into a powerful AI-driven
architecture analyzer that detects problems, suggests fixes, and provides
intelligent insights about code quality, performance issues, and architectural
drift. This elevates the "arrows between dots" concept into a living system
that actively improves the codebase.

Where: Connects to introspection.py for graph foundation, evolution_engine.py
for learning patterns, debug_config.py for performance metrics, and all Python
modules for comprehensive analysis. Powers enhanced graph visualization and
provides actionable recommendations.

How: Uses advanced AST parsing, dependency analysis, performance correlation,
pattern recognition, and machine learning to analyze code relationships and
suggest improvements. Integrates with existing graph system while adding
layers of intelligence.

Connects to:
    - introspection.py: Base graph system and runtime state
    - evolution_engine.py: Learning patterns and usage analytics
    - debug_config.py: Performance monitoring and error tracking
    - app.py: Flask route analysis and endpoint optimization
    - database.py: Query pattern analysis and optimization suggestions
"""
from __future__ import annotations

import ast
import re
import statistics
from collections import defaultdict, deque
from dataclasses import dataclass, field

# Enhanced problem detection categories
PROBLEM_CATEGORIES = {
    "ARCHITECTURAL": {"severity": "HIGH", "color": "#ff4444"},
    "PERFORMANCE": {"severity": "MEDIUM", "color": "#ff8800"},
    "DOCUMENTATION": {"severity": "LOW", "color": "#ffcc00"},
    "SECURITY": {"severity": "CRITICAL", "color": "#cc0000"},
    "COUPLING": {"severity": "MEDIUM", "color": "#ff6600"},
    "COMPLEXITY": {"severity": "MEDIUM", "color": "#ffaa00"},
    "OPTIMIZATION": {"severity": "LOW", "color": "#4488ff"},
}


@dataclass
class AnalysisResult:
    """Structured result from intelligent code analysis.

    Why: Provide standardized format for analysis findings that can power
    both CLI tools and interactive graph visualizations.
    Where: Used throughout analysis engine and returned to graph renderer.
    How: Dataclass with severity levels, categories, and actionable fixes.
    """

    node_id: str
    category: str
    title: str
    description: str
    severity: str
    confidence: float  # 0.0 to 1.0
    fix_suggestions: List[str] = field(default_factory=list)
    code_examples: List[str] = field(default_factory=list)
    performance_impact: Optional[str] = None
    related_nodes: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)


@dataclass
class ArchitecturalInsight:
    """High-level architectural pattern or anti-pattern detection.

    Why: Capture system-wide patterns that span multiple components and
    require coordinated fixes across the codebase.
    Where: Generated by cross-module analysis and displayed in graph overview.
    How: Aggregates findings across components to identify system patterns.
    """

    pattern_name: str
    description: str
    affected_components: List[str]
    impact_assessment: str
    recommended_actions: List[str]
    urgency: str  # LOW, MEDIUM, HIGH, CRITICAL
    estimated_effort: str  # HOURS, DAYS, WEEKS
    business_impact: str


class IntelligentAnalyzer:
    """
    Advanced code analysis engine that enhances the graph system.

    Why: Provide AI-powered insights that go beyond static documentation
    to actively identify problems, suggest optimizations, and guide
    architectural decisions based on usage patterns and code quality.
    Where: Integrates with existing introspection system to enhance graph
    data with intelligent analysis results and recommendations.
    How: Combines AST analysis, performance correlation, pattern matching,
    and heuristic evaluation to generate actionable insights.
    """

    def __init__(self):
        self._cache: Dict[str, Any] = {}
        self._analysis_history: deque = deque(maxlen=1000)
        self._performance_correlations: Dict[str, List[float]] = defaultdict(list)
        self._lock = threading.Lock()
        self._project_root = Path(__file__).parent

    def analyze_codebase(self, include_files: Optional[List[str]] = None) -> Dict[str, Any]:
        """
        Perform comprehensive analysis of the entire codebase.

        Why: Generate a complete picture of code quality, architectural
        patterns, and improvement opportunities across all components.
        Where: Called by enhanced runtime_state to power intelligent graph.
        How: Orchestrates multiple analysis passes and correlates findings.
        """
        with self._lock:
            results = {
                "analysis_results": [],
                "architectural_insights": [],
                "performance_recommendations": [],
                "security_findings": [],
                "optimization_opportunities": [],
                "dependency_analysis": {},
                "complexity_metrics": {},
                "quality_score": 0.0,
                "trend_analysis": {},
                "generated_at": time.time(),
            }

            try:
                # Get list of Python files to analyze
                files_to_analyze = self._get_analysis_targets(include_files)

                for file_path in files_to_analyze:
                    file_results = self._analyze_file(file_path)
                    results["analysis_results"].extend(file_results)

                # Cross-file analysis
                results["architectural_insights"] = self._detect_architectural_patterns(
                    files_to_analyze
                )
                results["dependency_analysis"] = self._analyze_dependencies(files_to_analyze)
                results["performance_recommendations"] = self._analyze_performance_patterns()
                results["security_findings"] = self._security_analysis(files_to_analyze)
                results["optimization_opportunities"] = self._find_optimization_opportunities(
                    files_to_analyze
                )
                results["complexity_metrics"] = self._calculate_complexity_metrics(files_to_analyze)
                results["quality_score"] = self._calculate_quality_score(results)
                results["trend_analysis"] = self._analyze_trends()

                # Store in history for trend analysis
                self._analysis_history.append(
                    {
                        "timestamp": time.time(),
                        "quality_score": results["quality_score"],
                        "issue_count": len(results["analysis_results"]),
                        "high_severity_count": len(
                            [r for r in results["analysis_results"] if r.severity == "HIGH"]
                        ),
                    }
                )

            except Exception:
                results["error"] = f"Analysis failed: {str(e)}"

            return results

    def _get_analysis_targets(self, include_files: Optional[List[str]]) -> List[Path]:
        """Get list of Python files to analyze."""
        if include_files:
            return [Path(f) for f in include_files if Path(f).suffix == ".py"]

        # Default: analyze main Python files
        targets = []
        for pattern in ["*.py", "tools/*.py", "tests/*.py"]:
            targets.extend(self._project_root.glob(pattern))

        # Exclude some patterns
        excludes = {"__pycache__", ".git", "venv", "node_modules"}
        return [p for p in targets if not any(ex in str(p) for ex in excludes)]

    def _analyze_file(self, file_path: Path) -> List[AnalysisResult]:
        """
        Analyze a single Python file for issues and opportunities.

        Why: Deep-dive analysis of individual components to identify
        specific problems, documentation gaps, and improvement areas.
        Where: Called for each file during codebase analysis.
        How: Uses AST parsing, regex analysis, and heuristic evaluation.
        """
        results = []

        try:
            content = file_path.read_text(encoding="utf-8", errors="ignore")
            tree = ast.parse(content)

            # Documentation analysis
            results.extend(self._analyze_documentation(file_path, content, tree))

            # Code quality analysis
            results.extend(self._analyze_code_quality(file_path, content, tree))

            # Performance analysis
            results.extend(self._analyze_performance_patterns_file(file_path, content, tree))

            # Security analysis
            results.extend(self._analyze_security_file(file_path, content, tree))

            # Architecture analysis
            results.extend(self._analyze_architecture_file(file_path, content, tree))

        except Exception:
            results.append(
                AnalysisResult(
                    node_id=str(file_path),
                    category="ARCHITECTURAL",
                    title="Parse Error",
                    description=f"Failed to parse {file_path}: {str(e)}",
                    severity="MEDIUM",
                    confidence=1.0,
                    fix_suggestions=["Check for syntax errors", "Verify file encoding"],
                )
            )

        return results

    def _analyze_documentation(
        self, file_path: Path, content: str, tree: ast.AST
    ) -> List[AnalysisResult]:
        """Analyze Why/Where/How documentation quality and completeness."""
        results = []

        # Check for Why/Where/How patterns
        why_count = len(re.findall(r"\b[Ww]hy\s*:", content))
        where_count = len(re.findall(r"\b[Ww]here\s*:", content))
        how_count = len(re.findall(r"\b[Hh]ow\s*:", content))

        functions = [node for node in ast.walk(tree) if isinstance(node, ast.FunctionDef)]
        classes = [node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)]

        total_definitions = len(functions) + len(classes)

        if total_definitions > 0:
            doc_coverage = (why_count + where_count + how_count) / (total_definitions * 3)

            if doc_coverage < 0.5:
                results.append(
                    AnalysisResult(
                        node_id=str(file_path),
                        category="DOCUMENTATION",
                        title="Insufficient Why/Where/How Documentation",
                        description=f"Only {doc_coverage:.1%} documentation coverage. Missing reasoning arrows.",
                        severity="MEDIUM",
                        confidence=0.9,
                        fix_suggestions=[
                            "Add Why: comments explaining business purpose",
                            "Add Where: comments describing component connections",
                            "Add How: comments detailing technical implementation",
                            'Use "Connects to:" sections to document dependencies',
                        ],
                    )
                )

        # Check for undocumented functions
        for func in functions:
            if not ast.get_docstring(func):
                results.append(
                    AnalysisResult(
                        node_id=f"{file_path}::{func.name}",
                        category="DOCUMENTATION",
                        title="Missing Function Documentation",
                        description=f"Function {func.name} lacks docstring with Why/Where/How",
                        severity="LOW",
                        confidence=0.8,
                        fix_suggestions=[f"Add comprehensive docstring to {func.name}()"],
                    )
                )

        return results

    def _analyze_code_quality(
        self, file_path: Path, content: str, tree: ast.AST
    ) -> List[AnalysisResult]:
        """Analyze code quality issues and anti-patterns."""
        results = []

        # Check for long functions
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                func_lines = node.end_lineno - node.lineno if hasattr(node, "end_lineno") else 0
                if func_lines > 50:
                    results.append(
                        AnalysisResult(
                            node_id=f"{file_path}::{node.name}",
                            category="COMPLEXITY",
                            title="Function Too Long",
                            description=f"Function {node.name} is {func_lines} lines (>50 recommended)",
                            severity="MEDIUM",
                            confidence=0.7,
                            fix_suggestions=[
                                "Break into smaller, focused functions",
                                "Extract complex logic into separate methods",
                                "Consider using helper functions or classes",
                            ],
                        )
                    )

        # Check for deeply nested code
        class NestingVisitor(ast.NodeVisitor):
            def __init__(self):
                self.max_depth = 0
                self.current_depth = 0

            def visit_If(self, node):
                self.current_depth += 1
                self.max_depth = max(self.max_depth, self.current_depth)
                self.generic_visit(node)
                self.current_depth -= 1

            visit_For = visit_While = visit_With = visit_If

        nesting = NestingVisitor()
        nesting.visit(tree)

        if nesting.max_depth > 4:
            results.append(
                AnalysisResult(
                    node_id=str(file_path),
                    category="COMPLEXITY",
                    title="Excessive Nesting",
                    description=f"Maximum nesting depth: {nesting.max_depth} (>4 recommended)",
                    severity="MEDIUM",
                    confidence=0.8,
                    fix_suggestions=[
                        "Use early returns to reduce nesting",
                        "Extract nested logic into separate functions",
                        "Consider guard clauses and defensive programming",
                    ],
                )
            )

        return results

    def _analyze_performance_patterns_file(
        self, file_path: Path, content: str, tree: ast.AST
    ) -> List[AnalysisResult]:
        """Analyze performance anti-patterns in a single file."""
        results = []

        # Check for inefficient patterns
        if re.search(r"for\s+\w+\s+in\s+.*\.keys\(\)", content):
            results.append(
                AnalysisResult(
                    node_id=str(file_path),
                    category="PERFORMANCE",
                    title="Inefficient Dictionary Iteration",
                    description="Using .keys() in for loop is inefficient",
                    severity="LOW",
                    confidence=0.9,
                    fix_suggestions=['Use "for key in dict:" instead of "for key in dict.keys()"'],
                    performance_impact="Minor CPU improvement",
                )
            )

        # Check for repeated string concatenation
        if re.search(r'\w+\s*\+=\s*["\'].*["\']', content):
            results.append(
                AnalysisResult(
                    node_id=str(file_path),
                    category="PERFORMANCE",
                    title="String Concatenation in Loop",
                    description="String concatenation with += can be slow in loops",
                    severity="MEDIUM",
                    confidence=0.7,
                    fix_suggestions=[
                        'Use list.append() and "".join() for multiple concatenations',
                        "Consider f-strings for formatting",
                        "Use io.StringIO for complex string building",
                    ],
                    performance_impact="Significant improvement for large strings",
                )
            )

        return results

    def _analyze_security_file(
        self, file_path: Path, content: str, tree: ast.AST
    ) -> List[AnalysisResult]:
        """Analyze security issues in a single file."""
        results = []

        # Check for potential SQL injection (basic)
        if re.search(r'execute\s*\(\s*[f]?["\'].*%.*["\']', content):
            results.append(
                AnalysisResult(
                    node_id=str(file_path),
                    category="SECURITY",
                    title="Potential SQL Injection Risk",
                    description="String formatting in SQL execute() calls can be dangerous",
                    severity="HIGH",
                    confidence=0.6,
                    fix_suggestions=[
                        "Use parameterized queries with ? placeholders",
                        "Validate and sanitize all user inputs",
                        "Consider using an ORM for complex queries",
                    ],
                )
            )

        # Check for hardcoded secrets
        secret_patterns = [
            r'password\s*=\s*["\'][^"\']+["\']',
            r'secret\s*=\s*["\'][^"\']+["\']',
            r'api_key\s*=\s*["\'][^"\']+["\']',
        ]

        for pattern in secret_patterns:
            if re.search(pattern, content, re.IGNORECASE):
                results.append(
                    AnalysisResult(
                        node_id=str(file_path),
                        category="SECURITY",
                        title="Hardcoded Credentials",
                        description="Potential hardcoded credentials found",
                        severity="CRITICAL",
                        confidence=0.8,
                        fix_suggestions=[
                            "Move credentials to environment variables",
                            "Use configuration files outside version control",
                            "Consider using a secrets management system",
                        ],
                    )
                )

        return results

    def _analyze_architecture_file(
        self, file_path: Path, content: str, tree: ast.AST
    ) -> List[AnalysisResult]:
        """Analyze architectural patterns and violations."""
        results = []

        # Check for circular imports (basic detection)
        imports = []
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                imports.extend([alias.name for alias in node.names])
            elif isinstance(node, ast.ImportFrom) and node.module:
                imports.append(node.module)

        # Check if this file might be part of circular dependency
        file_stem = file_path.stem
        if any(file_stem in imp for imp in imports):
            results.append(
                AnalysisResult(
                    node_id=str(file_path),
                    category="ARCHITECTURAL",
                    title="Potential Circular Import",
                    description=f"File {file_stem} may be part of circular dependency chain",
                    severity="HIGH",
                    confidence=0.5,
                    fix_suggestions=[
                        "Review import structure for circular dependencies",
                        "Consider dependency injection or late imports",
                        "Refactor shared code into separate modules",
                    ],
                )
            )

        return results

    def _detect_architectural_patterns(self, files: List[Path]) -> List[ArchitecturalInsight]:
        """Detect system-wide architectural patterns and anti-patterns."""
        insights = []

        # Analyze overall file structure
        py_files = len(files)
        if py_files > 50:
            insights.append(
                ArchitecturalInsight(
                    pattern_name="Large Codebase",
                    description=f"Codebase has {py_files} Python files, consider modularization",
                    affected_components=[str(f) for f in files[:10]],  # Sample
                    impact_assessment="May impact maintainability and onboarding",
                    recommended_actions=[
                        "Group related functionality into packages",
                        "Create clear module boundaries",
                        "Document high-level architecture",
                    ],
                    urgency="MEDIUM",
                    estimated_effort="WEEKS",
                    business_impact="Improved developer productivity and code maintainability",
                )
            )

        # Check for missing test files
        test_files = [f for f in files if "test" in str(f)]
        non_test_files = [f for f in files if "test" not in str(f)]
        test_coverage_ratio = len(test_files) / max(1, len(non_test_files))

        if test_coverage_ratio < 0.3:
            insights.append(
                ArchitecturalInsight(
                    pattern_name="Low Test Coverage",
                    description=f"Test to source file ratio: {test_coverage_ratio:.1%}",
                    affected_components=[str(f) for f in non_test_files[:5]],
                    impact_assessment="High risk of regressions and bugs",
                    recommended_actions=[
                        "Add unit tests for core functionality",
                        "Implement integration tests for workflows",
                        "Set up automated testing pipeline",
                    ],
                    urgency="HIGH",
                    estimated_effort="WEEKS",
                    business_impact="Reduced bugs, faster development, improved reliability",
                )
            )

        return insights

    def _analyze_dependencies(self, files: List[Path]) -> Dict[str, Any]:
        """Analyze dependency relationships and coupling."""
        dependencies = defaultdict(set)

        for file_path in files:
            try:
                content = file_path.read_text(encoding="utf-8", errors="ignore")
                tree = ast.parse(content)

                imports = []
                for node in ast.walk(tree):
                    if isinstance(node, ast.Import):
                        imports.extend([alias.name for alias in node.names])
                    elif isinstance(node, ast.ImportFrom) and node.module:
                        imports.append(node.module)

                dependencies[str(file_path)] = set(imports)
            except:
                continue

        # Calculate coupling metrics
        total_deps = sum(len(deps) for deps in dependencies.values())
        avg_dependencies = total_deps / max(1, len(dependencies))

        return {
            "total_files": len(dependencies),
            "total_dependencies": total_deps,
            "average_dependencies_per_file": avg_dependencies,
            "highly_coupled_files": [
                file for file, deps in dependencies.items() if len(deps) > avg_dependencies * 1.5
            ],
            "dependency_graph": {k: list(v) for k, v in dependencies.items()},
        }

    def _analyze_performance_patterns(self) -> List[AnalysisResult]:
        """Analyze performance patterns from historical data."""
        results = []

        # Correlate with performance monitoring if available
        try:
            from debug_config import performance_monitor_registry

            if hasattr(performance_monitor_registry, "get_stats"):
                stats = performance_monitor_registry.get_stats()
                for func_name, timings in stats.items():
                    if len(timings) > 5:
                        avg_time = statistics.mean(timings)
                        if avg_time > 100:  # >100ms average
                            results.append(
                                AnalysisResult(
                                    node_id=func_name,
                                    category="PERFORMANCE",
                                    title="Slow Function Detected",
                                    description=f"Function {func_name} averages {avg_time:.1f}ms",
                                    severity="MEDIUM",
                                    confidence=0.9,
                                    fix_suggestions=[
                                        "Profile function for bottlenecks",
                                        "Consider caching frequently computed results",
                                        "Optimize database queries or I/O operations",
                                    ],
                                    performance_impact=f"Potential {avg_time:.0f}ms improvement per call",
                                )
                            )
        except:
            pass  # Performance monitoring not available

        return results

    def _security_analysis(self, files: List[Path]) -> List[AnalysisResult]:
        """Perform system-wide security analysis."""
        results = []

        # Check for Flask app security settings
        for file_path in files:
            if file_path.name == "app.py":
                try:
                    content = file_path.read_text()
                    if "debug=True" in content and "production" not in content.lower():
                        results.append(
                            AnalysisResult(
                                node_id=str(file_path),
                                category="SECURITY",
                                title="Debug Mode in Production Risk",
                                description="Flask debug mode may be enabled in production",
                                severity="HIGH",
                                confidence=0.7,
                                fix_suggestions=[
                                    "Use environment variables to control debug mode",
                                    "Ensure debug=False in production deployment",
                                    "Add explicit production/development configuration",
                                ],
                            )
                        )
                except:
                    pass

        return results

    def _find_optimization_opportunities(self, files: List[Path]) -> List[AnalysisResult]:
        """Find potential optimization opportunities."""
        results = []

        # Look for database query patterns
        for file_path in files:
            try:
                content = file_path.read_text()

                # Check for N+1 query patterns
                if re.search(r"for\s+\w+\s+in.*:\s*.*\.execute\(", content, re.MULTILINE):
                    results.append(
                        AnalysisResult(
                            node_id=str(file_path),
                            category="OPTIMIZATION",
                            title="Potential N+1 Query Pattern",
                            description="Database queries inside loops can cause performance issues",
                            severity="MEDIUM",
                            confidence=0.6,
                            fix_suggestions=[
                                "Consider batch queries or joins",
                                "Use eager loading for related data",
                                "Cache frequently accessed data",
                            ],
                            performance_impact="Significant database performance improvement",
                        )
                    )

            except:
                continue

        return results

    def _calculate_complexity_metrics(self, files: List[Path]) -> Dict[str, Any]:
        """Calculate complexity metrics for the codebase."""
        total_lines = 0
        total_functions = 0
        max_complexity = 0

        for file_path in files:
            try:
                content = file_path.read_text()
                lines = len([l for l in content.splitlines() if l.strip()])
                total_lines += lines

                tree = ast.parse(content)
                functions = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
                total_functions += len(functions)

                # Simple cyclomatic complexity approximation
                for func in functions:
                    complexity = 1  # base complexity
                    for node in ast.walk(func):
                        if isinstance(node, (ast.If, ast.For, ast.While, ast.ExceptHandler)):
                            complexity += 1
                    max_complexity = max(max_complexity, complexity)

            except:
                continue

        return {
            "total_lines_of_code": total_lines,
            "total_functions": total_functions,
            "average_lines_per_function": total_lines / max(1, total_functions),
            "maximum_complexity": max_complexity,
            "complexity_rating": (
                "LOW" if max_complexity < 10 else "MEDIUM" if max_complexity < 20 else "HIGH"
            ),
        }

    def _calculate_quality_score(self, analysis_results: Dict[str, Any]) -> float:
        """Calculate overall codebase quality score (0-100)."""
        base_score = 100.0

        # Deduct points for issues
        for result in analysis_results["analysis_results"]:
            if result.severity == "CRITICAL":
                base_score -= 15
            elif result.severity == "HIGH":
                base_score -= 8
            elif result.severity == "MEDIUM":
                base_score -= 4
            elif result.severity == "LOW":
                base_score -= 1

        # Bonus for good documentation coverage
        doc_issues = [
            r for r in analysis_results["analysis_results"] if r.category == "DOCUMENTATION"
        ]
        if len(doc_issues) < 5:  # Few documentation issues
            base_score += 5

        return max(0.0, min(100.0, base_score))

    def _analyze_trends(self) -> Dict[str, Any]:
        """Analyze quality and issue trends over time."""
        if len(self._analysis_history) < 2:
            return {"message": "Insufficient data for trend analysis"}

        history = list(self._analysis_history)
        recent = history[-5:]  # Last 5 analyses

        quality_trend = "stable"
        if len(recent) >= 2:
            recent_scores = [h["quality_score"] for h in recent]
            if recent_scores[-1] > recent_scores[0] + 5:
                quality_trend = "improving"
            elif recent_scores[-1] < recent_scores[0] - 5:
                quality_trend = "declining"

        return {
            "quality_trend": quality_trend,
            "current_quality_score": recent[-1]["quality_score"] if recent else 0,
            "total_analyses": len(history),
            "average_issues_per_analysis": statistics.mean([h["issue_count"] for h in history]),
            "trend_period_days": (history[-1]["timestamp"] - history[0]["timestamp"]) / 86400,
        }


# Global analyzer instance
_intelligent_analyzer = IntelligentAnalyzer()


def get_intelligent_analysis(
    include_files: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """
    Get comprehensive intelligent analysis of the codebase.

    Why: Provide the main interface for accessing AI-powered code analysis
    that identifies problems, suggests fixes, and guides improvements.
    Where: Called by enhanced introspection system and graph visualization.
    How: Delegates to IntelligentAnalyzer for comprehensive codebase analysis.

    Connects to:
        - introspection.py: Enhanced runtime state with intelligent insights
        - graph-debug.js: Visual problem highlighting and recommendations
    """
    return _intelligent_analyzer.analyze_codebase(include_files)


def analyze_single_component(component_path: str) -> List[AnalysisResult]:
    """
    Analyze a single component for targeted insights.

    Why: Enable focused analysis when working on specific components
    or responding to user questions about particular files.
    Where: Used by interactive graph tools and targeted analysis requests.
    How: Runs subset of analysis engine on single file or component.
    """
    path = Path(component_path)
    if path.exists():
        return _intelligent_analyzer._analyze_file(path)
    return []


def get_fix_recommendations(node_id: str, category: str) -> Dict[str, Any]:
    """
    Get detailed fix recommendations for a specific issue.

    Why: Provide actionable, detailed guidance for resolving identified
    problems with code examples and step-by-step instructions.
    Where: Called by graph UI when user clicks on problem nodes.
    How: Generates contextual recommendations based on issue type and location.
    """
    recommendations = {
        "DOCUMENTATION": {
            "why_missing": [
                'Add "Why:" comment explaining business purpose',
                "Consider user needs and system goals",
                "Document decision rationale and trade-offs",
            ],
            "where_missing": [
                'Add "Where:" comment describing connections',
                "List dependent components and data flow",
                "Document integration points and APIs used",
            ],
            "how_missing": [
                'Add "How:" comment explaining implementation',
                "Describe algorithms and data structures used",
                "Document assumptions and edge cases",
            ],
        },
        "PERFORMANCE": {
            "slow_function": [
                "Profile with cProfile to identify bottlenecks",
                "Consider caching frequently computed values",
                "Optimize database queries and I/O operations",
                "Use async/await for I/O-bound operations",
            ],
            "inefficient_loops": [
                "Use list comprehensions where appropriate",
                "Consider vectorized operations with NumPy",
                "Cache loop-invariant computations",
                "Break early when possible",
            ],
        },
        "SECURITY": {
            "sql_injection": [
                'Use parameterized queries: cursor.execute("SELECT * FROM table WHERE id = ?", (user_id,))',
                "Validate and sanitize all user inputs",
                "Use whitelist validation for user data",
                "Consider using an ORM like SQLAlchemy",
            ],
            "hardcoded_secrets": [
                'Move secrets to environment variables: os.getenv("SECRET_KEY")',
                "Use .env files with python-dotenv",
                "Consider AWS Secrets Manager or similar",
                "Add .env to .gitignore",
            ],
        },
    }

    return {
        "node_id": node_id,
        "category": category,
        "recommendations": recommendations.get(category, {}),
        "generated_at": time.time(),
    }
