name: Dependency Security Checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0'

jobs:
  python-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip-audit
        run: pip install pip-audit
      - name: Audit Python dependencies
        run: pip-audit -r requirements.txt || true

  js-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci || npm install
      - name: Audit JS dependencies
        run: npm audit || true
