name: Update File Inventory

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-inventory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements-min.txt || true
      - name: Generate file inventory
        run: |
          source .venv/bin/activate
          make file-inventory
      - name: Commit and push inventory
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add file-inventory.md
          git commit -m "Auto-update file inventory" || echo "No changes"
          git push || true
